### ISSUE TITLE
How to generate code for multiple databases?

### ISSUE THREAD

**Issue by costa100** [cmeeren/Facil#21]
Hi,

Because I am stuck to .net 5 for now, I am using Facil 1.4.3. How do I handle multiple databases? According to the docs, I can have multiple yaml files. I created two yaml files facil_db1.yaml, facil_db2.yaml, but the build process complains:

`Error		No config file found. A minimal config file has been placed in the project directory (D:\TestDbAccess\facil.yaml). Re-build after editing the config.	TestDbAccess	D:\TestDbAccess\Facil	1	`

Also, it seems that there is a build hook that calls the facil generator, but I am not sure how I can override that command in case it supports specifying the yaml file name.

Thank you

Update: One option would be to create two library projects, one for each database and then reference these.

**Comment by cmeeren** [comment]
You can not have multiple files. You have several config sections in the single file. To be specific, as you can see in the reference yaml file, `rulesets` is an array. Just add another array item to generate another file.

**Comment by costa100** [comment]
Yes, please. I read this:

> See the full YAML config reference for details. Note that you can generate multiple source files with separate configs (e.g. to generate from multiple DBs). Here are some highlights of what you can configure.

And I thought you need to specify different files.

Quick question, if I want to define two connection strings, do I need to specify this:
```
configs:
  - envVars: ""

rulesets:
  - connectionString: Data Source=sddbshrcs01;Initial Catalog=db1;Integrated Security=True

    namespaceOrModuleDeclaration: module Db1

    tableScripts:
      - include: dbo.Table1
        
        scripts:
          - type: insert
          - type: update
          - type: merge
          - type: getById
            
    tableDtos:
        - include: .*
          except: cdc\..*
          
  - connectionString: Data Source=sddbshrcs01;Initial Catalog=db2;Integrated Security=True

    filename: DbGenDb2.fs
    namespaceOrModuleDeclaration: namespace Db2

    tableScripts:
      - include: dbo.Table2
        scripts:
          - type: insert
          - type: update
          - type: merge
          - type: getById
            
    tableDtos:
        - include: .*
          except: cdc\..*  
```
 I tried it, and the generation tool complained:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		System.Exception: Error getting table DTOs	TestDbAccess	D:\TestDbAccess\Facil	1	
```

**Comment by costa100** [comment]
Yes, please. I read this:

> See the full YAML config reference for details. Note that you can generate multiple source files with separate configs (e.g. to generate from multiple DBs). Here are some highlights of what you can configure.

I thought I need to specify different files.

Quick question, if I want to define two connection strings, do I need to specify this:
```
configs:
  - envVars: ""

rulesets:
  - connectionString: Data Source=server1;Initial Catalog=db1;Integrated Security=True

    namespaceOrModuleDeclaration: module Db1

    tableScripts:
      - include: dbo.Table1
        
        scripts:
          - type: insert
          - type: update
          - type: merge
          - type: getById
            
    tableDtos:
        - include: .*
          except: cdc\..*
          
  - connectionString: Data Source=server1;Initial Catalog=db2;Integrated Security=True

    filename: DbGenDb2.fs
    namespaceOrModuleDeclaration: namespace Db2

    tableScripts:
      - include: dbo.Table2
        scripts:
          - type: insert
          - type: update
          - type: merge
          - type: getById
            
    tableDtos:
        - include: .*
          except: cdc\..*  
```
 I tried it, and the generation tool complained:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		System.Exception: Error getting table DTOs	TestDbAccess	D:\TestDbAccess\Facil	1	
```

**Comment by cmeeren** [comment]
That YAML looks right to me. Not sure what's wrong. Is that the only error message you get? The exception should have an inner exception; I would think that too should be printed.

**Comment by costa100** [comment]
I took a look with the sql profiler to see what happens and the tool stopped after running this:


```
      SELECT
        SCHEMA_NAME(sys.tables.schema_id) AS SchemaName,
        sys.tables.name AS TableName,
        sys.all_columns.name AS ColName,
        sys.all_columns.column_id,
        sys.all_columns.is_nullable,
        sys.all_columns.system_type_id,
        sys.all_columns.max_length,
        sys.all_columns.precision,
        sys.all_columns.scale,
        sys.all_columns.is_identity,
        sys.all_columns.is_computed,
        IsView = CAST(0 AS BIT)
      FROM
        sys.tables
      INNER JOIN
        sys.all_columns
          ON sys.all_columns.object_id = sys.tables.object_id

      UNION

      SELECT
        SCHEMA_NAME(sys.views.schema_id) AS SchemaName,
        sys.views.name AS TableName,
        sys.all_columns.name AS ColName,
        sys.all_columns.column_id,
        sys.all_columns.is_nullable,
        sys.all_columns.system_type_id,
        sys.all_columns.max_length,
        sys.all_columns.precision,
        sys.all_columns.scale,
        sys.all_columns.is_identity,
        sys.all_columns.is_computed,
        IsView = CAST(1 AS BIT)
      FROM
        sys.views
      INNER JOIN
        sys.all_columns
          ON sys.all_columns.object_id = sys.views.object_id
    
```
Btw, the union can be converted to an union ALL - it saves some time.

Yes, fails with this:
`---> System.Exception: Unsupported SQL type 'sql_variant' for column 'Value' in table 'MapPropertyValue'`
This is ok, it is a different issue. The tables that I have to edit don't have sql_variant columns. So, it is all good for now.

**Comment by cmeeren** [comment]
> it might be nice to support sql_variant columns in the future.

That will both be non-trivial and go very much against the grain of Facil's strongly typed goals, since it will require Facil to provide a way to retrieve the column value as any type on a per-row basis, essentially wrapping `SqlDataReader`'s numerous methods. I might consider it if someone posts a feature request with a well explained use-case and some guidance on the expected functionality, but no promises.

In any case, I have updated the readme now, so AFAIK there is nothing more outstanding in this issue. Feel free to correct me if I have missed anything.

**Comment by cmeeren** [comment]
Indeed Facil only checks that for tables that are being processed. If you look carefully at your YAML, I'm guessing that there is an `include` value that covers the `ContractMapPropertyValue` table, and that if this rule has an `except` value, that value does not cover (i.e., does not exclude) that table.

**Comment by cmeeren** [comment]
Side-note (not relevant here, but nice to know): You can exclude specific columns, too, so if you need to work with a table that has `sql_variant` but you don't actually need the `sql_variant` column, then that is possible.

**Comment by costa100** [comment]
> Indeed Facil only checks that for tables that are being processed. If you look carefully at your YAML, I'm guessing that there is an `include` value for the table DTOs that covers the `ContractMapPropertyValue` table, and that if this rule has an `except` value, that value does not cover (i.e., does not exclude) that table.

This is the content of yaml file for this database:
```
  - connectionString: Data Source=server1;Initial Catalog=db1;Integrated Security=True

    filename: DbDb1.fs
    namespaceOrModuleDeclaration: namespace db1

    #procedures:
      # Generate wrappers for all stored procedures with the default configuration.
    #  - include: .*
    tableScripts:
      - include: dbo.Table1
        #except: dbo\.SomeTable

        scripts:

            # Generates a script to insert a row.
          - type: insert
          - type: update
          - type: merge
          - type: getById
            
    tableDtos:
        - include: dbo\.Table2
          #except: cdc\..*     
```  

Table1 & Table2 don't include sql_variant columns. That is why I thought the check is done early. Unless i am doing something wrong.

**Comment by cmeeren** [comment]
Thanks, I'll have a look at it.

**Comment by cmeeren** [comment]
I have confirmed the bug (which affects only table DTOs, not e.g. table scripts). Will fix tomorrow. However, it will of course require .NET 6.

As a workaround, you can add a rule for the problematic table that explicitly skips the sql_variant column. That should work on 1.x.

**Comment by costa100** [comment]
Thank you!!

The workaround you suggested works. I had to include the table and then exclude the sql_variant column:
```
        - include: dbo\.ContractMapPropertyValue    
          columns:
              Value:
                skip: true

``` 
I tried:
```
        - include: dbo\.ContractMapPropertyValue    
          except: dbo\.ContractMapPropertyValue

``` 
but it doesn't seem to do the trick.
