### ISSUE TITLE
Facil strips off additional sql statements from temp table script

### ISSUE THREAD

**Issue by costa100** [cmeeren/Facil#29]
Hello,

I have the following:

```
    scripts:
      - include: "*.sql"
      - for: TempJobTemplate.sql
        tempTables:
          - definition: CreateTable/TempJobTemplate.sql
      
```
In the CreateTable/TempJobTemplate.sql script I have the create table statement followed by a create index statement (I did not use a "go" between the statements, I ended the create table statement with semicolon). The create index statement is removed from the ~~script~~ generated code, even though I want it there. Is it normal? What can I do to tell Facil to leave it there?

Thanks

Edited: I added the folder the name to the script name.
