### ISSUE TITLE
Version 2.3.1 raising error when using connectionString: $([Variable Name])

### ISSUE THREAD

**Issue by mauriciomagni** [cmeeren/Facil#38]
After updating to version 2.3.1, it started raising an error when trying to generate DbGen file, saying:
facil.yaml(0 , 0) : error : The variable $(Db) could not be found in the specified configuration sources

Going back to version 2.3.0 works as expected.

In my facil.yaml file I have this configuration:
```
rulesets:
  - connectionString: $(Db)
```

**Comment by cmeeren** [comment]
I can't reproduce. The following works fine in Facil's test project:

```yaml
configs:
  - appSettings: appsettings.json

rulesets:
  - connectionString: $(connectionString)
```

I need a minimal repro. Could you create one?
