### ISSUE TITLE
Suggestion - Allow file paths in facil.yaml to be case insensitive

### ISSUE THREAD

**Issue by davidtme** [cmeeren/Facil#5]
At the moment if the case is incorrect within the facil.yaml, generation might not work. I ran into this with the following config:

```
rulesets:
  - connectionString: Data Source=.;Initial Catalog=Db;Integrated Security=True

    scripts:
      - include: "**/*.sql"
        except: Sql/ReadingsMergeTemp.sql

      - for: Sql/ReadingsMerge.sql
        tempTables: 
          - definition: "SQL/ReadingsMergeTemp.sql"
		  
```

_tempTables/definition_ Sql is upper case so wasn't found.
