### ISSUE TITLE
Unmanaged memory leaks when executing repeated calls to the DB

### ISSUE THREAD

**Issue by mikkor14** [cmeeren/Facil#59]
I am using Facil for my DB/Repo logic in my Giraffe WebAPI, using mostly User Defined Functions that i call as .sql scripts to fetch data from the DB. I noticed that when running the API, each request i make increases the unmanaged memory heap, without GC. This becomes quite problematic with large data sets (15 000+ rows). Here is a graph showing the unmanaged memory heap growing with each request:
![image](https://github.com/cmeeren/Facil/assets/21168842/7b69f5ba-6022-4838-a526-35df16ed8c25)

I am using Facil in a separate project from the API, as a Class Lib like so:
-	DataAccess.fsproj
	-	DbGen.fs
	-	Repo.fs
- API.fsproj
	- Controllers
		- PriceController.fs 

My Facil.yaml looks like this:
```
  - connectionString: "MyConnString"
    filename: DbGen.fs
    namespaceOrModuleDeclaration: module DbGen
    
    # The base path for all scripts (including temp table definitions) in this ruleset,
    # relative to the project directory.
    scriptBasePath: ./SQL/Prices
    
    
    scripts:
      - include: '**/*.sql'
        except:

        # The following work exactly like they do in stored procedure rules.
        result: auto
        paramDto: inline
        voptionIn: false
        voptionOut: false
        recordIfSingleCol: false

      - for: GetPrices.sql
        result: nominal
        params:
          Currency:
            type: CHAR
          TimeZone:
            type: CHAR
          FromDate:
            type: DATE
          ToDate:
            type: DATE
          Resolution:
            type: CHAR
```
I am using .sql scripts to call UDFs as recommended, example of calling the one called **GetPrices:**
`select * from [myPrices].[GetPrices]  (@currency, @timeZone, @dateFrom, @dateTo, @timeResolution )`

Function to call the script is located in the Repo.fs, and looks like this:

```
        let getPrices (connString: string) (currency : string) (timeZone : string) (dateFrom: DateTime) (dateTo: DateTime) (resolution: string) =
            GetPrices
                                 .WithConnection(connString)
                                 .WithParameters(currency, timeZone, dateFrom, dateTo, timeResolution)
                                 .AsyncExecute()
```
I am then calling it from the API, passing in the parameters and handling the result in an async handler, then serialize the result with JSON. For testing purposes i mostly did it like this:

```
                Repo.getPrices connString currency timeZone dateFrom dateTo timeResolution
                |> Async.RunSynchronously
                |> Seq.toList
```

It is unfortunately difficult for me to provide an accurate DB schema due to privacy issues, but it is a Microsoft SQL Server hosted on Azure. Example for returned data for the UDF shown in the example (returns around 18 000 rows of data):

```
  {
    "indeks": 0,
    "Product": "NO1",
    "TimeStartUTC": "2020-12-31T23:00:00",
    "Resolution": "H",
    "unit": "EUR/h",
    "Price": "24.950000"
  },
  {
    "indeks": 1,
    "Product": null,
    "TimeStartUTC": null,
    "Resolution": null,
    "unit": null,
    "Price": "24.350000"
  },
  {
    "indeks": 2,
    "Product": null,
    "TimeStartUTC": null,
    "Resolution": null,
    "unit": null,
    "Price": "23.980000"
  },
```

This problem does not lie within the UDF itself, as all my other UDF's and scripts also leak memory, so i do not think that showing the SQL query for the UDF is necessary here.

I have tried using the provided **AsyncExecuteReader** method, and disposing it afterwards like so:
`use repo = Repo.GetPrices`
As well as opening a connection with SqlConnection, and passing it to the **WithConnection** function, but it gave no results
