### ISSUE TITLE
Parameter does not exist in any matching scripts for SQL scripts calling UDF's

### ISSUE THREAD

**Issue by mikkor14** [cmeeren/Facil#60]
Hello! I have a DB with a bunch of UDF's and as recommended i am calling them from a script like so:
`select *from [myDb].GetPrices(@user, @currency)`

The function shown in the example is declared in my DB:
`CREATE function [myDb].[GetPrices]  (@user varchar(256), @currency varchar(32))`

In my Facil.yaml, i have the script defined like so:

```
    scripts:
      - include: '**/*.sql'

        result: auto
        paramDto: skip
        voptionIn: false
        voptionOut: false
        recordIfSingleCol: false
        
      - for: PricesGet.sql
        result: nominal
        params:
          user:
            type: VARCHAR
          currency:
            type: VARCHAR
            nullable: true
```

But when building my project, i am getting a warning `Script rule at index 1 with for = 'PricesGet.sql' has a rule for parameter 'user', but the parameter does not exist in any matching scripts`. I am doing something wrong? I have tried declaring the variables before the SELECT statement `(declare @user VARCHAR;)`, but i still get the same warning and cannot use them after generation

**Comment by cmeeren** [comment]
I need a more complete example. As a start, could you share a minimal example of the script? This should be a script that produces the error during generation, but does not contain any more code not relevant to the reproduction.

**Comment by mikkor14** [comment]
I am calling the UDF with the SELECT statement provided above,
 `select *from [myDb].GetPrices(@user, @currency)`, it is called PricesGet.sql and is inside the project folder. I tested the script by just hardcoding the param values, and it works fine. 
I tried renaming the variables, and it seemed to help, but now i just get no data from my function. If you want to recreate it yourself, be sure to name all variables the same across the UDF, SQL script and Facil config, i suspect there might be something there

**Comment by cmeeren** [comment]
Hi, I am happy to help, but I need a minimal reproducible example I can look at to investigate. I have never myself had any problem calling UDFs like that, so likely something is wrong on your end. However, without seeing a minimal script that reproduces the error, I can't tell you what might be wrong.

**Comment by mikkor14** [comment]
I think you are misunderstanding, this is my script, i have nothing besides this SELECT statement interacting with the UDF. Do you mean the UDF code? It is just a generic `SELECT [data] FROM [core].[PriceDb] WHERE user = @user`. I have other UDF's as well, and none of them return any data if their parameter names are matching the ones defined in the SQL script and Facil. 
Just to be clear, here is all the code that i am currently running:
PricesGet.sql:
` select *from [myDb].GetPrices(@user, @currency)`
```
Facil.yaml:
    scripts:
      - include: '**/*.sql'

        result: auto
        paramDto: skip
        voptionIn: false
        voptionOut: false
        recordIfSingleCol: false
        
      - for: PricesGet.sql
        result: nominal
        params:
          user:
            type: VARCHAR
          currency:
            type: VARCHAR
            nullable: true
```
DBAccess.fs:
```
        let getPrice (connString: string) (user: string option) (currency: string option) =
            PricesGet
                .WithConnection(connString)
                .WithParameters(user, currency)
                .ExecuteAsync()
```
The code inside the UDF is provided above, but is not relevant since i get no data from any of my UDF's if i am using params in this way
